# Generated by Django 3.2 on 2021-04-27 09:46

from django.db import migrations, models
import regex_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegularExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', regex_field.fields.RegexField(max_length=256)),
            ],
            options={
                'verbose_name': 'RegularExpression',
                'verbose_name_plural': 'RegularExpressions',
                'db_table': 'regular_expression',
            },
        ),
    ]
